/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Leirbag
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userlbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        livrosLbl = new javax.swing.JLabel();
        emprestimolbl = new javax.swing.JLabel();
        alunoslbl = new javax.swing.JLabel();
        livroslbl = new javax.swing.JLabel();
        multaslbl = new javax.swing.JLabel();
        sairBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        livrosBtn = new javax.swing.JButton();
        AlunosBtn = new javax.swing.JButton();
        FuncionariosBtn = new javax.swing.JButton();
        EmprestimosBtn = new javax.swing.JButton();
        DevolucaoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 210, 190));

        userlbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userlbl.setForeground(java.awt.Color.white);
        userlbl.setText("Usuário Logado");

        jPanel2.setBackground(new java.awt.Color(7, 138, 133));

        livrosLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        livrosLbl.setForeground(new java.awt.Color(255, 255, 255));
        livrosLbl.setText("Total de livros: ");

        emprestimolbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emprestimolbl.setForeground(new java.awt.Color(255, 255, 255));
        emprestimolbl.setText("Empréstimo ativos: ");

        alunoslbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alunoslbl.setForeground(new java.awt.Color(255, 255, 255));
        alunoslbl.setText("Total de alunos: ");

        livroslbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        livroslbl.setForeground(new java.awt.Color(255, 255, 255));
        livroslbl.setText("Livros em atraso: ");

        multaslbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        multaslbl.setForeground(new java.awt.Color(255, 255, 255));
        multaslbl.setText("Multas pendentes:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(multaslbl)
                    .addComponent(livroslbl)
                    .addComponent(alunoslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(livrosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emprestimolbl))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(livrosLbl)
                .addGap(18, 18, 18)
                .addComponent(alunoslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emprestimolbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(livroslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(multaslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        sairBtn.setBackground(new java.awt.Color(232, 30, 74));
        sairBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sairBtn.setForeground(new java.awt.Color(255, 255, 255));
        sairBtn.setText("Sair");
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(7, 138, 133));

        livrosBtn.setBackground(new java.awt.Color(232, 30, 74));
        livrosBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        livrosBtn.setForeground(new java.awt.Color(255, 255, 255));
        livrosBtn.setText("Livros");
        livrosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                livrosBtnActionPerformed(evt);
            }
        });

        AlunosBtn.setBackground(new java.awt.Color(232, 30, 74));
        AlunosBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlunosBtn.setForeground(new java.awt.Color(255, 255, 255));
        AlunosBtn.setText("Alunos");
        AlunosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunosBtnActionPerformed(evt);
            }
        });

        FuncionariosBtn.setBackground(new java.awt.Color(232, 30, 74));
        FuncionariosBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FuncionariosBtn.setForeground(new java.awt.Color(255, 255, 255));
        FuncionariosBtn.setText("Funcionários");
        FuncionariosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuncionariosBtnActionPerformed(evt);
            }
        });

        EmprestimosBtn.setBackground(new java.awt.Color(232, 30, 74));
        EmprestimosBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmprestimosBtn.setForeground(new java.awt.Color(255, 255, 255));
        EmprestimosBtn.setText("Empréstimos");
        EmprestimosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmprestimosBtnActionPerformed(evt);
            }
        });

        DevolucaoBtn.setBackground(new java.awt.Color(232, 30, 74));
        DevolucaoBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DevolucaoBtn.setForeground(new java.awt.Color(255, 255, 255));
        DevolucaoBtn.setText("Devolução");
        DevolucaoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolucaoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlunosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FuncionariosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(livrosBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmprestimosBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(DevolucaoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(livrosBtn)
                .addGap(39, 39, 39)
                .addComponent(AlunosBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(FuncionariosBtn)
                .addGap(44, 44, 44)
                .addComponent(EmprestimosBtn)
                .addGap(41, 41, 41)
                .addComponent(DevolucaoBtn)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sairBtn)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(62, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sairBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sairBtnActionPerformed

    private void livrosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_livrosBtnActionPerformed
       new TelaLivros().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_livrosBtnActionPerformed

    private void AlunosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunosBtnActionPerformed
        new TelaAlunos().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_AlunosBtnActionPerformed

    private void FuncionariosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuncionariosBtnActionPerformed
        new TelaFuncionarios().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_FuncionariosBtnActionPerformed

    private void EmprestimosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmprestimosBtnActionPerformed
        new TelaEmprestimo().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_EmprestimosBtnActionPerformed

    private void DevolucaoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolucaoBtnActionPerformed
        new TelaDevolucao().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_DevolucaoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlunosBtn;
    private javax.swing.JButton DevolucaoBtn;
    private javax.swing.JButton EmprestimosBtn;
    private javax.swing.JButton FuncionariosBtn;
    private javax.swing.JLabel alunoslbl;
    private javax.swing.JLabel emprestimolbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton livrosBtn;
    private javax.swing.JLabel livrosLbl;
    private javax.swing.JLabel livroslbl;
    private javax.swing.JLabel multaslbl;
    private javax.swing.JButton sairBtn;
    private javax.swing.JLabel userlbl;
    // End of variables declaration//GEN-END:variables
}
